"""DynamicSdkAdapter — a runtime-generated adapter for any robot hardware.

运动皮层 (Motor Cortex): codegen-friendly adapter.

When a user describes their robot, the motor cortex agent:
1. Converses with the user to understand the hardware and SDK
2. Generates Python code for the five adapter methods
3. Calls `DynamicSdkAdapter.from_spec()` to create an in-memory adapter
4. Calls `AdapterRegistry.register()` to persist it to disk
5. From then on it is loaded automatically via `AdapterRegistry.load_all()`

The generated code is stored at:
  ~/.local/share/eaib/adapters/<body_id>/adapter.py

It must export a top-level class named `Adapter(BaseSdkAdapter)`.
"""

from __future__ import annotations

import importlib.util
import logging
import sys
import textwrap
from pathlib import Path
from typing import Any

from deerflow.eaib.motor_cortex.sdk_adapters.base_adapter import BaseSdkAdapter, ConnectionStatus

logger = logging.getLogger(__name__)

_ADAPTER_CLASS_NAME = "Adapter"

# Template shown to the motor cortex agent when generating a new adapter
ADAPTER_CODE_TEMPLATE = '''"""
SDK adapter for {body_id}.

Auto-generated by the EAIB motor cortex.
Fill in each method based on the target robot's SDK documentation.
"""

from __future__ import annotations
from typing import Any
from deerflow.eaib.motor_cortex.sdk_adapters.base_adapter import BaseSdkAdapter, ConnectionStatus


class Adapter(BaseSdkAdapter):
    """SDK adapter for {body_id}."""

    @property
    def body_id(self) -> str:
        return "{body_id}"

    @property
    def sdk_package(self) -> str:
        # e.g. "my_robot_sdk" or a GitHub URL
        return "{sdk_package}"

    @property
    def sdk_import_name(self) -> str:
        # Python import name to verify installation
        return "{sdk_import_name}"

    def connect(self, **kwargs: Any) -> ConnectionStatus:
        # TODO: implement connection logic
        raise NotImplementedError("connect() not yet implemented")

    def get_state(self) -> dict[str, Any]:
        # TODO: return current robot state (joints, battery, sensors, …)
        raise NotImplementedError("get_state() not yet implemented")

    def emergency_stop(self) -> bool:
        # TODO: implement emergency stop
        raise NotImplementedError("emergency_stop() not yet implemented")
'''


class DynamicSdkAdapter(BaseSdkAdapter):
    """An adapter loaded from a dynamically generated Python module.

    Do not instantiate directly — use `DynamicSdkAdapter.from_file()`.
    The motor cortex agent should use `AdapterRegistry` which calls this internally.
    """

    def __init__(self, delegate: BaseSdkAdapter) -> None:
        super().__init__()
        self._delegate = delegate

    # --- Delegation to generated class ---

    @property
    def body_id(self) -> str:
        return self._delegate.body_id

    @property
    def sdk_package(self) -> str:
        return self._delegate.sdk_package

    @property
    def sdk_import_name(self) -> str:
        return self._delegate.sdk_import_name

    def connect(self, **kwargs: Any) -> ConnectionStatus:
        return self._delegate.connect(**kwargs)

    def get_state(self) -> dict[str, Any]:
        return self._delegate.get_state()

    def emergency_stop(self) -> bool:
        return self._delegate.emergency_stop()

    # --- Factory ---

    @classmethod
    def from_file(cls, adapter_path: Path) -> "DynamicSdkAdapter":
        """Load an `Adapter` class from a Python file and return a wrapped instance.

        Args:
            adapter_path: Path to a Python file exporting a class named `Adapter`.

        Raises:
            ImportError: If the file does not define `Adapter` or it fails to import.
            TypeError: If `Adapter` is not a `BaseSdkAdapter` subclass.
        """
        module_name = f"eaib_dynamic_adapter_{adapter_path.parent.name}"
        spec = importlib.util.spec_from_file_location(module_name, str(adapter_path))
        if spec is None or spec.loader is None:
            raise ImportError(f"Cannot create module spec from {adapter_path}")

        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)  # type: ignore[union-attr]

        adapter_cls = getattr(module, _ADAPTER_CLASS_NAME, None)
        if adapter_cls is None:
            raise ImportError(f"{adapter_path} must define a top-level class named '{_ADAPTER_CLASS_NAME}'")
        if not (isinstance(adapter_cls, type) and issubclass(adapter_cls, BaseSdkAdapter)):
            raise TypeError(f"'{_ADAPTER_CLASS_NAME}' in {adapter_path} must subclass BaseSdkAdapter")

        instance = adapter_cls()
        logger.info("Loaded dynamic adapter for body_id='%s' from %s", instance.body_id, adapter_path)
        return cls(instance)

    @staticmethod
    def render_template(body_id: str, sdk_package: str = "UNKNOWN", sdk_import_name: str = "UNKNOWN") -> str:
        """Return a filled-in adapter code template for the agent to edit."""
        return ADAPTER_CODE_TEMPLATE.format(
            body_id=body_id,
            sdk_package=sdk_package,
            sdk_import_name=sdk_import_name,
        )
